apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.name" . }}
  labels:
    app: {{ include "k8s.name" . }}
    chart: {{ include "k8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    releaseVersion: {{ include "k8s.appVersion" . }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "k8s.name" . }}
    release: {{ .Release.Name }}
